[package]
name = "roasted"
version = "0.1.0"
authors = ["Nurahmadie <177826+fudanchii@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
